# driver_path: msedgedriver.exe
driver_path: chromedriver-win64/chromedriver-win64/chromedriver.exe
# driver_path: ./msedgedriver.exe
# driver_path: chromedriver-win64/chromedriver-win64/chromedriver.exe

BMI_test:
    TC-001-001:
        age: 20
        height: 170
        weight: 60
        gender: male

        bmi_value: 20.8
        status: Healthy weight

    TC-001-002:
        age: 30
        height: 160
        weight: 55
        gender: female

        bmi_value: 21.5
        status: Normal

    TC-001-003:
        age: 1
        height: 180
        weight: 80
        gender: male

        bmi_value: Null

    TC-001-004:
        age: 121
        height: 180
        weight: 80
        gender: male

        bmi_value: Null


    TC-001-005:
        age: 80
        height: 180
        weight: 80
        gender: male

        bmi_value: 24.7
        status: Normal

    TC-001-006:
        age: 119
        height: 180
        weight: 80
        gender: male

        bmi_value: 24.7
        status: Normal

    TC-001-007:
        age: 3
        height: 180
        weight: 80
        gender: male

        bmi_value: 24.7
        status: Overweight

    TC-001-008:
        age: 80
        height: 180
        weight: 0
        gender: male

        bmi_value: Null




Body_fat_test:
    TC-002-001:
        age: 23
        height: 182
        weight: 71
        gender: male
        neck: 34
        waist: 80

        body_fat: 15.0


    TC-002-002:
        age: -1
        height: -1
        weight: -1
        gender: male
        neck: -1
        waist: -1

        body_fat: Null

    TC-002-003:
        age: Null
        height: Null
        weight: Null
        gender: male
        neck: Null
        waist: Null

        body_fat: Null

    TC-002-004:
        age: 25
        height: 175
        weight: 75
        gender: male
        neck: Null
        waist: Null

        body_fat: Null


    TC-002-005:
        age: 70
        height: 155
        weight: 60
        gender: female   
        neck: Null
        waist: Null

        body_fat: Null


    TC-002-006:
        age: 0
        height: 140
        weight: 80
        gender: male
        neck: Null
        waist: Null

        body_fat: Null


























